Name:           perl-Net-Zabbix
Version:        2.00
Release:        1%{?dist}
Summary:        Net::Zabbix Perl module
License:        WTF-PL
Group:          Development/Libraries
URL:            https://github.com/ksyz/Net-Zabbix
Source0:        https://github.com/ksyz/Net-Zabbix/archive/v2.tar.gz
BuildArch:      noarch
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(JSON::PP)
BuildRequires:  perl(LWP)
BuildRequires:  perl(LWP::Protocol::https)
BuildRequires:  perl(Net::DNS)
BuildRequires:  perl(Net::IP)
BuildRequires:  perl(Net::SNMP)
BuildRequires:  perl(Net::SSL)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Time::HiRes)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Net::Zabbix is simple and thin layer between Zabbix API and your code. It
doesn't implement much, except authentication and request counting. There
are few helper methods to simplify calling methods such as
create/get/update/delete/exists. There is no checking of method parameters,
as that is work for-and already implemented on server side.

%prep
%setup -q -n Net-Zabbix-2

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
make pure_install PERL_INSTALL_ROOT=%{buildroot}

find %{buildroot} -type f -name .packlist -exec rm -f {} \;
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
%doc NOTES README.md
%{perl_vendorlib}/*

%changelog
* Thu Dec 10 2015 Michal Ingeli <mi@v3.sk> 2.00-1
- Specfile autogenerated by cpanspec 1.78.
